export const ANALYST_DC_DATA = [
  {
    taskId: '0001',
    pillar: 'Enviromental',
    company: 'Reliance Ltd',
    fiscalYear: '2018-2019',
    status: 'Yet to start',
    dpCodesData: [
      {
        dpCode: 'AUDP001',
        fiscalYear: '2018-2019',
        status: 'Completed',
        description: 'Does the board member hold a seat in the audit committee ?',
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'text',
        keyIssue: 'Shareholders rights',
        historicalData: [
          {
            dpCode: 'AUDP001',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Does the board member hold a seat in the audit committee ?',
            dataType: 'text',
            textSnippet: 'Snippet One',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'AUDP001',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Does the board member hold a seat in the audit committee ?',
            dataType: 'text',
            textSnippet: 'Snippet Two',
            pageNo: '24',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'No',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 05 2016' },
          },
        ],
      },
      {
        dpCode: 'BOCR013',
        fiscalYear: '2018-2019',
        status: 'Completed',
        description: "Board member's fixed cash based compensation",
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'number',
        keyIssue: 'Audit committee functioning',
        historicalData: [
          {
            dpCode: 'BOCR013',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: "Board member's fixed cash based compensation",
            dataType: 'number',
            textSnippet: 'Snippet One',
            pageNo: '58',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '21321',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BOCR013',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: "Board member's fixed cash based compensation",
            dataType: 'number',
            textSnippet: 'Snippet Two',
            pageNo: '24',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '213123',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
      {
        dpCode: 'BOIR017',
        fiscalYear: '2018-2019',
        status: 'Yet to start',
        description: 'Board member date of appointment',
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'date',
        keyIssue: 'Audit committee functioning',
        historicalData: [
          {
            dpCode: 'BOIR017',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Board member date of appointment',
            dataType: 'date',
            textSnippet: 'Snippet One',
            pageNo: '58',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BOIR017',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Board member date of appointment',
            dataType: 'date',
            textSnippet: 'Snippet Two',
            pageNo: '42',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
    ],
  },
  {
    taskId: '0002',
    pillar: 'Social',
    company: 'Reliance Ltd',
    fiscalYear: '2018-2019',
    status: 'In progress',
    dpCodesData: [
      {
        dpCode: 'AUDP001',
        fiscalYear: '2018-2019',
        status: 'Completed',
        description: 'Does the board member hold a seat in the audit committee ?',
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'text',
        keyIssue: 'Shareholders rights',
        historicalData: [
          {
            dpCode: 'AUDP001',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Does the board member hold a seat in the audit committee ?',
            dataType: 'text',
            textSnippet: 'Snippet One',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'AUDP001',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Does the board member hold a seat in the audit committee ?',
            dataType: 'text',
            textSnippet: 'Snippet Two',
            pageNo: '24',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'No',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
      {
        dpCode: 'BOCR013',
        fiscalYear: '2018-2019',
        status: 'Completed',
        description: "Board member's fixed cash based compensation",
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'number',
        keyIssue: 'Audit committee functioning',
        historicalData: [
          {
            dpCode: 'BOCR013',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: "Board member's fixed cash based compensation",
            dataType: 'number',
            textSnippet: 'Snippet One',
            pageNo: '58',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '21321',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BOCR013',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: "Board member's fixed cash based compensation",
            dataType: 'number',
            textSnippet: 'Snippet Two',
            pageNo: '24',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '213123',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
      {
        dpCode: 'BOIR017',
        fiscalYear: '2018-2019',
        status: 'Yet to start',
        description: 'Board member date of appointment',
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'date',
        keyIssue: 'Audit committee functioning',
        historicalData: [
          {
            dpCode: 'BOIR017',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Board member date of appointment',
            dataType: 'date',
            textSnippet: 'Snippet One',
            pageNo: '58',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BOIR017',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Board member date of appointment',
            dataType: 'date',
            textSnippet: 'Snippet Two',
            pageNo: '42',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
    ],
  },
  {
    taskId: '0003',
    pillar: 'Governance',
    company: 'Reliance Ltd',
    fiscalYear: '2018-2019',
    status: 'Submitted',
    dpCodesData: [
      {
        dpCode: 'AUDP001',
        fiscalYear: '2018-2019',
        status: 'Completed',
        description: 'Does the board member hold a seat in the audit committee ?',
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'text',
        keyIssue: 'Shareholders rights',
        historicalData: [
          {
            dpCode: 'AUDP001',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Does the board member hold a seat in the audit committee ?',
            dataType: 'text',
            textSnippet: 'Snippet One',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'AUDP001',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Does the board member hold a seat in the audit committee ?',
            dataType: 'text',
            textSnippet: 'Snippet Two',
            pageNo: '24',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'No',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
      {
        dpCode: 'BOCR013',
        fiscalYear: '2018-2019',
        status: 'Completed',
        description: "Board member's fixed cash based compensation",
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'number',
        keyIssue: 'Audit committee functioning',
        historicalData: [
          {
            dpCode: 'BOCR013',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: "Board member's fixed cash based compensation",
            dataType: 'number',
            textSnippet: 'Snippet One',
            pageNo: '58',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '21321',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BOCR013',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: "Board member's fixed cash based compensation",
            dataType: 'number',
            textSnippet: 'Snippet Two',
            pageNo: '24',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '213123',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
      {
        dpCode: 'BOIR017',
        fiscalYear: '2018-2019',
        status: 'Yet to start',
        description: 'Board member date of appointment',
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'date',
        keyIssue: 'Audit committee functioning',
        historicalData: [
          {
            dpCode: 'BOIR017',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Board member date of appointment',
            dataType: 'date',
            textSnippet: 'Snippet One',
            pageNo: '58',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BOIR017',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Board member date of appointment',
            dataType: 'date',
            textSnippet: 'Snippet Two',
            pageNo: '42',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
    ],
  },
];

export const QA_DV_DATA = [
  {
    taskId: '0001',
    pillar: 'Enviromental',
    company: 'Reliance Ltd',
    fiscalYear: '2018-2019',
    status: 'Yet to start',
    dpCodesData: [
      {
        dpCode: 'AUDP001',
        fiscalYear: '2018-2019',
        status: 'Completed',
        description: 'Does the board member hold a seat in the audit committee ?',
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'text',
        keyIssue: 'Shareholders rights',
        textSnippet: 'Snippet One',
        pageNo: '59',
        screenShot: 'https://esgds.io/images/home/logo.png',
        response: 'Yes',
        screen: 'Na',
        source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
        historicalData: [
          {
            dpCode: 'AUDP001',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Does the board member hold a seat in the audit committee ?',
            dataType: 'text',
            textSnippet: 'Snippet One',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'AUDP001',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Does the board member hold a seat in the audit committee ?',
            dataType: 'text',
            textSnippet: 'Snippet Two',
            pageNo: '24',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'No',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 05 2016' },
          },
        ],
      },
      {
        dpCode: 'BOCR013',
        fiscalYear: '2018-2019',
        status: 'Completed',
        description: "Board member's fixed cash based compensation",
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'number',
        keyIssue: 'Audit committee functioning',
        textSnippet: 'Snippet One',
        pageNo: '58',
        screenShot: 'https://esgds.io/images/home/logo.png',
        response: '21321',
        screen: 'Na',
        source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
        historicalData: [
          {
            dpCode: 'BOCR013',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: "Board member's fixed cash based compensation",
            dataType: 'number',
            textSnippet: 'Snippet One',
            pageNo: '58',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '21321',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BOCR013',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: "Board member's fixed cash based compensation",
            dataType: 'number',
            textSnippet: 'Snippet Two',
            pageNo: '24',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '213123',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
      {
        dpCode: 'BOIR017',
        fiscalYear: '2018-2019',
        status: 'Yet to start',
        description: 'Board member date of appointment',
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'date',
        keyIssue: 'Audit committee functioning',
        textSnippet: 'Snippet One',
        pageNo: '58',
        screenShot: 'https://esgds.io/images/home/logo.png',
        response: 'Tue May 01 2016',
        screen: 'Na',
        source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
        historicalData: [
          {
            dpCode: 'BOIR017',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Board member date of appointment',
            dataType: 'date',
            textSnippet: 'Snippet One',
            pageNo: '58',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BOIR017',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Board member date of appointment',
            dataType: 'date',
            textSnippet: 'Snippet Two',
            pageNo: '42',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
    ],
  },
  {
    taskId: '0002',
    pillar: 'Social',
    company: 'Reliance Ltd',
    fiscalYear: '2018-2019',
    status: 'In progress',
    dpCodesData: [
      {
        dpCode: 'AUDP001',
        fiscalYear: '2018-2019',
        status: 'Completed',
        description: 'Does the board member hold a seat in the audit committee ?',
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'text',
        keyIssue: 'Shareholders rights',
        textSnippet: 'Snippet One',
        pageNo: '59',
        screenShot: 'https://esgds.io/images/home/logo.png',
        response: 'Yes',
        screen: 'Na',
        source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
        historicalData: [
          {
            dpCode: 'AUDP001',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Does the board member hold a seat in the audit committee ?',
            dataType: 'text',
            textSnippet: 'Snippet One',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'AUDP001',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Does the board member hold a seat in the audit committee ?',
            dataType: 'text',
            textSnippet: 'Snippet Two',
            pageNo: '24',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'No',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
      {
        dpCode: 'BOCR013',
        fiscalYear: '2018-2019',
        status: 'Completed',
        description: "Board member's fixed cash based compensation",
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'number',
        keyIssue: 'Audit committee functioning',
        textSnippet: 'Snippet One',
        pageNo: '58',
        screenShot: 'https://esgds.io/images/home/logo.png',
        response: '21321',
        screen: 'Na',
        source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
        historicalData: [
          {
            dpCode: 'BOCR013',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: "Board member's fixed cash based compensation",
            dataType: 'number',
            textSnippet: 'Snippet One',
            pageNo: '58',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '21321',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BOCR013',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: "Board member's fixed cash based compensation",
            dataType: 'number',
            textSnippet: 'Snippet Two',
            pageNo: '24',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '213123',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
      {
        dpCode: 'BOIR017',
        fiscalYear: '2018-2019',
        status: 'Yet to start',
        description: 'Board member date of appointment',
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'date',
        keyIssue: 'Audit committee functioning',
        textSnippet: 'Snippet One',
        pageNo: '58',
        screenShot: 'https://esgds.io/images/home/logo.png',
        response: 'Tue May 01 2016',
        screen: 'Na',
        source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
        historicalData: [
          {
            dpCode: 'BOIR017',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Board member date of appointment',
            dataType: 'date',
            textSnippet: 'Snippet One',
            pageNo: '58',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BOIR017',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Board member date of appointment',
            dataType: 'date',
            textSnippet: 'Snippet Two',
            pageNo: '42',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
    ],
  },
  {
    taskId: '0003',
    pillar: 'Governance',
    company: 'Reliance Ltd',
    fiscalYear: '2018-2019',
    status: 'Submitted',
    dpCodesData: [
      {
        dpCode: 'AUDP001',
        fiscalYear: '2018-2019',
        status: 'Completed',
        description: 'Does the board member hold a seat in the audit committee ?',
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'text',
        keyIssue: 'Shareholders rights',
        textSnippet: 'Snippet One',
        pageNo: '59',
        screenShot: 'https://esgds.io/images/home/logo.png',
        response: 'Yes',
        screen: 'Na',
        source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
        historicalData: [
          {
            dpCode: 'AUDP001',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Does the board member hold a seat in the audit committee ?',
            dataType: 'text',
            textSnippet: 'Snippet One',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'AUDP001',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Does the board member hold a seat in the audit committee ?',
            dataType: 'text',
            textSnippet: 'Snippet Two',
            pageNo: '24',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'No',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
      {
        dpCode: 'BOCR013',
        fiscalYear: '2018-2019',
        status: 'Completed',
        description: "Board member's fixed cash based compensation",
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'number',
        keyIssue: 'Audit committee functioning',
        textSnippet: 'Snippet One',
        pageNo: '58',
        screenShot: 'https://esgds.io/images/home/logo.png',
        response: '21321',
        screen: 'Na',
        source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
        historicalData: [
          {
            dpCode: 'BOCR013',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: "Board member's fixed cash based compensation",
            dataType: 'number',
            textSnippet: 'Snippet One',
            pageNo: '58',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '21321',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BOCR013',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: "Board member's fixed cash based compensation",
            dataType: 'number',
            textSnippet: 'Snippet Two',
            pageNo: '24',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '213123',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
      {
        dpCode: 'BOIR017',
        fiscalYear: '2018-2019',
        status: 'Yet to start',
        description: 'Board member date of appointment',
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'date',
        keyIssue: 'Audit committee functioning',
        textSnippet: 'Snippet One',
        pageNo: '58',
        screenShot: 'https://esgds.io/images/home/logo.png',
        response: 'Tue May 01 2016',
        screen: 'Na',
        source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
        historicalData: [
          {
            dpCode: 'BOIR017',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Board member date of appointment',
            dataType: 'date',
            textSnippet: 'Snippet One',
            pageNo: '58',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BOIR017',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Board member date of appointment',
            dataType: 'date',
            textSnippet: 'Snippet Two',
            pageNo: '42',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
    ],
  },
];

export const COMPANY_REP_DATA = [
  {
    taskId: '0001',
    pillar: 'Enviromental',
    company: 'Reliance Ltd',
    fiscalYear: '2018-2019',
    status: 'Yet to start',
    dpCodesData: [
      {
        dpCode: 'AUDP001',
        fiscalYear: '2018-2019',
        status: 'Completed',
        description: 'Does the board member hold a seat in the audit committee ?',
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'text',
        keyIssue: 'Shareholders rights',
        textSnippet: 'Snippet One',
        pageNo: '59',
        screenShot: 'https://esgds.io/images/home/logo.png',
        response: 'Yes',
        screen: 'Na',
        source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
        historicalData: [
          {
            dpCode: 'AUDP001',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Does the board member hold a seat in the audit committee ?',
            dataType: 'text',
            textSnippet: 'Snippet One',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'AUDP001',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Does the board member hold a seat in the audit committee ?',
            dataType: 'text',
            textSnippet: 'Snippet Two',
            pageNo: '24',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'No',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 05 2016' },
          },
        ],
      },
      {
        dpCode: 'BOCR013',
        fiscalYear: '2018-2019',
        status: 'Completed',
        description: "Board member's fixed cash based compensation",
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'number',
        keyIssue: 'Audit committee functioning',
        textSnippet: 'Snippet One',
        pageNo: '58',
        screenShot: 'https://esgds.io/images/home/logo.png',
        response: '21321',
        screen: 'Na',
        source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
        historicalData: [
          {
            dpCode: 'BOCR013',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: "Board member's fixed cash based compensation",
            dataType: 'number',
            textSnippet: 'Snippet One',
            pageNo: '58',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '21321',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BOCR013',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: "Board member's fixed cash based compensation",
            dataType: 'number',
            textSnippet: 'Snippet Two',
            pageNo: '24',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '213123',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
      {
        dpCode: 'BOIR017',
        fiscalYear: '2018-2019',
        status: 'Yet to start',
        description: 'Board member date of appointment',
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'date',
        keyIssue: 'Audit committee functioning',
        textSnippet: 'Snippet One',
        pageNo: '58',
        screenShot: 'https://esgds.io/images/home/logo.png',
        response: 'Tue May 01 2016',
        screen: 'Na',
        source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
        historicalData: [
          {
            dpCode: 'BOIR017',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Board member date of appointment',
            dataType: 'date',
            textSnippet: 'Snippet One',
            pageNo: '58',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BOIR017',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Board member date of appointment',
            dataType: 'date',
            textSnippet: 'Snippet Two',
            pageNo: '42',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
    ],
  },
  {
    taskId: '0002',
    pillar: 'Social',
    company: 'Reliance Ltd',
    fiscalYear: '2018-2019',
    status: 'In progress',
    dpCodesData: [
      {
        dpCode: 'AUDP001',
        fiscalYear: '2018-2019',
        status: 'Completed',
        description: 'Does the board member hold a seat in the audit committee ?',
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'text',
        keyIssue: 'Shareholders rights',
        textSnippet: 'Snippet One',
        pageNo: '59',
        screenShot: 'https://esgds.io/images/home/logo.png',
        response: 'Yes',
        screen: 'Na',
        source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
        historicalData: [
          {
            dpCode: 'AUDP001',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Does the board member hold a seat in the audit committee ?',
            dataType: 'text',
            textSnippet: 'Snippet One',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'AUDP001',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Does the board member hold a seat in the audit committee ?',
            dataType: 'text',
            textSnippet: 'Snippet Two',
            pageNo: '24',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'No',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
      {
        dpCode: 'BOCR013',
        fiscalYear: '2018-2019',
        status: 'Completed',
        description: "Board member's fixed cash based compensation",
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'number',
        keyIssue: 'Audit committee functioning',
        textSnippet: 'Snippet One',
        pageNo: '58',
        screenShot: 'https://esgds.io/images/home/logo.png',
        response: '21321',
        screen: 'Na',
        source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
        historicalData: [
          {
            dpCode: 'BOCR013',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: "Board member's fixed cash based compensation",
            dataType: 'number',
            textSnippet: 'Snippet One',
            pageNo: '58',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '21321',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BOCR013',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: "Board member's fixed cash based compensation",
            dataType: 'number',
            textSnippet: 'Snippet Two',
            pageNo: '24',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '213123',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
      {
        dpCode: 'BOIR017',
        fiscalYear: '2018-2019',
        status: 'Yet to start',
        description: 'Board member date of appointment',
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'date',
        keyIssue: 'Audit committee functioning',
        textSnippet: 'Snippet One',
        pageNo: '58',
        screenShot: 'https://esgds.io/images/home/logo.png',
        response: 'Tue May 01 2016',
        screen: 'Na',
        source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
        historicalData: [
          {
            dpCode: 'BOIR017',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Board member date of appointment',
            dataType: 'date',
            textSnippet: 'Snippet One',
            pageNo: '58',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BOIR017',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Board member date of appointment',
            dataType: 'date',
            textSnippet: 'Snippet Two',
            pageNo: '42',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
    ],
  },
  {
    taskId: '0003',
    pillar: 'Governance',
    company: 'Reliance Ltd',
    fiscalYear: '2018-2019',
    status: 'Submitted',
    dpCodesData: [
      {
        dpCode: 'AUDP001',
        fiscalYear: '2018-2019',
        status: 'Completed',
        description: 'Does the board member hold a seat in the audit committee ?',
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'text',
        keyIssue: 'Shareholders rights',
        textSnippet: 'Snippet One',
        pageNo: '59',
        screenShot: 'https://esgds.io/images/home/logo.png',
        response: 'Yes',
        screen: 'Na',
        source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
        historicalData: [
          {
            dpCode: 'AUDP001',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Does the board member hold a seat in the audit committee ?',
            dataType: 'text',
            textSnippet: 'Snippet One',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'AUDP001',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Does the board member hold a seat in the audit committee ?',
            dataType: 'text',
            textSnippet: 'Snippet Two',
            pageNo: '24',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'No',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
      {
        dpCode: 'BOCR013',
        fiscalYear: '2018-2019',
        status: 'Completed',
        description: "Board member's fixed cash based compensation",
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'number',
        keyIssue: 'Audit committee functioning',
        textSnippet: 'Snippet One',
        pageNo: '58',
        screenShot: 'https://esgds.io/images/home/logo.png',
        response: '21321',
        screen: 'Na',
        source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
        historicalData: [
          {
            dpCode: 'BOCR013',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: "Board member's fixed cash based compensation",
            dataType: 'number',
            textSnippet: 'Snippet One',
            pageNo: '58',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '21321',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BOCR013',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: "Board member's fixed cash based compensation",
            dataType: 'number',
            textSnippet: 'Snippet Two',
            pageNo: '24',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '213123',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
      {
        dpCode: 'BOIR017',
        fiscalYear: '2018-2019',
        status: 'Yet to start',
        description: 'Board member date of appointment',
        isStandAloneOrMatrix: 'Standalone',
        dataType: 'date',
        keyIssue: 'Audit committee functioning',
        textSnippet: 'Snippet One',
        pageNo: '58',
        screenShot: 'https://esgds.io/images/home/logo.png',
        response: 'Tue May 01 2016',
        screen: 'Na',
        source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
        historicalData: [
          {
            dpCode: 'BOIR017',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Board member date of appointment',
            dataType: 'date',
            textSnippet: 'Snippet One',
            pageNo: '58',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BOIR017',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Board member date of appointment',
            dataType: 'date',
            textSnippet: 'Snippet Two',
            pageNo: '42',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            screen: 'Na',
            source: { sourceName: 'Annual Report', url: 'https://www.hindustanpetroleum.com/documents/doc/HPCL%20Annual%20Report%202019-2020.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
      },
    ],
  },
];
