export const ANALYST_DC_DATA = [
  {
    taskId: '0001',
    pillar: 'Environmental',
    company: 'Manglore Refinery Petrochemicals Ltd',
    fiscalYear: '2018-2019, 2019-2020',
    status: 'Yet to start',
    dpCodesData: [
      {
        dpCode: 'BIOP002',
        fiscalYear: '2018-2019, 2019-2020',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        comments: [
          {
            author: 'Quality Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Company Representative', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
        ],
        currentData: [
          {
            dpCode: 'BIOP002',
            fiscalYear: '2018-2019',
            status: 'unknown',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
          },
          {
            dpCode: 'BIOP002',
            fiscalYear: '2019-2020',
            status: 'unknown',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
          },
        ],
        historicalData: [
          {
            dpCode: 'BIOP002',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BIOP002',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'No',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
      {
        dpCode: 'BION002',
        fiscalYear: '2018-2019, 2019-2020',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        currentData: [
          {
            dpCode: 'BION002',
            fiscalYear: '2018-2019',
            status: 'unknown',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
          },
          {
            dpCode: 'BION002',
            fiscalYear: '2019-2020',
            status: 'unknown',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
          },
        ],
        historicalData: [
          {
            dpCode: 'BION002',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '10000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BION002',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '23000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
      {
        dpCode: 'BION003',
        fiscalYear: '2018-2019, 2019-2020',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        currentData: [
          {
            dpCode: 'BION003',
            fiscalYear: '2018-2019',
            status: 'unknown',
            description: 'Fine Due Date',
            dataType: 'date',
          },
          {
            dpCode: 'BION003',
            fiscalYear: '2019-2020',
            status: 'unknown',
            description: 'Fine Due Date',
            dataType: 'date',
          },
        ],
        historicalData: [
          {
            dpCode: 'BION003',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2017',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BION003',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
    ],
  },
  {
    taskId: '0002',
    pillar: 'Social',
    company: 'Manglore Refinery Petrochemicals Ltd',
    fiscalYear: '2018-2019',
    status: 'In progress',
    dpCodesData: [
      {
        dpCode: 'BIOP002',
        fiscalYear: '2018-2019',
        status: 'Completed',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        currentData: [
          {
            dpCode: 'BIOP002',
            fiscalYear: '2018-2019',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
        ],
        historicalData: [
          {
            dpCode: 'BIOP002',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BIOP002',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'No',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
      {
        dpCode: 'BION002',
        fiscalYear: '2018-2019',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        currentData: [
          {
            dpCode: 'BION002',
            fiscalYear: '2018-2019',
            status: 'unknown',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
          },
        ],
        historicalData: [
          {
            dpCode: 'BION002',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '10000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BION002',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '23000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
      {
        dpCode: 'BION003',
        fiscalYear: '2018-2019',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        currentData: [
          {
            dpCode: 'BION003',
            fiscalYear: '2018-2019',
            status: 'unknown',
            description: 'Fine Due Date',
            dataType: 'date',
          },
        ],
        historicalData: [
          {
            dpCode: 'BION003',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2017',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BION003',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
    ],
  },
  {
    taskId: '0003',
    pillar: 'Governance',
    company: 'Manglore Refinery Petrochemicals Ltd',
    fiscalYear: '2018-2019, 2019-2020',
    status: 'Yet to start',
    dpCodesData: [
      {
        dpCode: 'BIOP002',
        fiscalYear: '2018-2019, 2019-2020',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        currentData: [
          {
            dpCode: 'BIOP002',
            fiscalYear: '2018-2019',
            status: 'unknown',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
          },
          {
            dpCode: 'BIOP002',
            fiscalYear: '2019-2020',
            status: 'unknown',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
          },
        ],
        historicalData: [
          {
            dpCode: 'BIOP002',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BIOP002',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'No',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
      {
        dpCode: 'BION002',
        fiscalYear: '2018-2019, 2019-2020',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        currentData: [
          {
            dpCode: 'BION002',
            fiscalYear: '2018-2019',
            status: 'unknown',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
          },
          {
            dpCode: 'BION002',
            fiscalYear: '2019-2020',
            status: 'unknown',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
          },
        ],
        historicalData: [
          {
            dpCode: 'BION002',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '10000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BION002',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '23000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
      {
        dpCode: 'BION003',
        fiscalYear: '2018-2019, 2019-2020',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        currentData: [
          {
            dpCode: 'BION003',
            fiscalYear: '2018-2019',
            status: 'unknown',
            description: 'Fine Due Date',
            dataType: 'date',
          },
          {
            dpCode: 'BION003',
            fiscalYear: '2019-2020',
            status: 'unknown',
            description: 'Fine Due Date',
            dataType: 'date',
          },
        ],
        historicalData: [
          {
            dpCode: 'BION003',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2017',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BION003',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
      {
        dpCode: 'BIOP009',
        fiscalYear: '2018-2019, 2019-2020',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Matrix',
        keyIssue: 'Management structure',
        currentData: [
          {
            dpCode: 'BIOP009',
            fiscalYear: '2018-2019',
            status: 'unknown',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
          },
          {
            dpCode: 'BIOP009',
            fiscalYear: '2019-2020',
            status: 'unknown',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
          },
        ],
        historicalData: [
          {
            dpCode: 'BIOP009',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BIOP009',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'No',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
    ],
  },
];

export const QA_DV_DATA = [
  {
    taskId: '0001',
    pillar: 'Environmental',
    company: 'Manglore Refinery Petrochemicals Ltd',
    fiscalYear: '2018-2019, 2019-2020',
    status: 'Yet to start',
    dpCodesData: [
      {
        dpCode: 'BIOP002',
        fiscalYear: '2018-2019, 2019-2020',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        comments: [
          {
            author: 'Quality Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Company Representative', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
        ],
        currentData: [
          {
            dpCode: 'BIOP002',
            fiscalYear: '2018-2019',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null, type: '', comment: '', errorStatus: 'Incomplete',
            },
          },
          {
            dpCode: 'BIOP002',
            fiscalYear: '2019-2020',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null, type: '', comment: '', errorStatus: 'Incomplete',
            },
          },
        ],
        historicalData: [
          {
            dpCode: 'BIOP002',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BIOP002',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'No',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
      {
        dpCode: 'BION002',
        fiscalYear: '2018-2019, 2019-2020',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        comments: [
          {
            author: 'Quality Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Company Representative', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
        ],
        currentData: [
          {
            dpCode: 'BION002',
            fiscalYear: '2018-2019',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '10000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null, type: '', comment: '', errorStatus: 'Incomplete',
            },
          },
          {
            dpCode: 'BION002',
            fiscalYear: '2019-2020',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '10000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null, type: '', comment: '', errorStatus: 'Incomplete',
            },
          },
        ],
        historicalData: [
          {
            dpCode: 'BION002',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '10000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BION002',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '23000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
      {
        dpCode: 'BION003',
        fiscalYear: '2018-2019, 2019-2020',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        comments: [
          {
            author: 'Quality Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Company Representative', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
        ],
        currentData: [
          {
            dpCode: 'BION003',
            fiscalYear: '2018-2019',
            status: 'unknown',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2017',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null, type: '', comment: '', errorStatus: 'Incomplete',
            },
          },
          {
            dpCode: 'BION003',
            fiscalYear: '2019-2020',
            status: 'unknown',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2017',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null, type: '', comment: '', errorStatus: 'Incomplete',
            },
          },
        ],
        historicalData: [
          {
            dpCode: 'BION003',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2017',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BION003',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
    ],
  },
  {
    taskId: '0002',
    pillar: 'Social',
    company: 'Manglore Refinery Petrochemicals Ltd',
    fiscalYear: '2018-2019',
    status: 'In progress',
    dpCodesData: [
      {
        dpCode: 'BIOP002',
        fiscalYear: '2018-2019',
        status: 'Completed',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        comments: [
          {
            author: 'Quality Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Company Representative', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
        ],
        currentData: [
          {
            dpCode: 'BIOP002',
            fiscalYear: '2018-2019',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: true, type: 'T1. Document missed', comment: 'Comment No 1', errorStatus: 'Completed',
            },
          },
        ],
        historicalData: [
          {
            dpCode: 'BIOP002',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BIOP002',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'No',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
      {
        dpCode: 'BION002',
        fiscalYear: '2018-2019',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        comments: [
          {
            author: 'Quality Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Company Representative', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
        ],
        currentData: [
          {
            dpCode: 'BION002',
            fiscalYear: '2018-2019',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '10000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null, type: '', comment: '', errorStatus: 'Incomplete',
            },
          },
        ],
        historicalData: [
          {
            dpCode: 'BION002',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '10000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BION002',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '23000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
      {
        dpCode: 'BION003',
        fiscalYear: '2018-2019',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        comments: [
          {
            author: 'Quality Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Company Representative', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
        ],
        currentData: [
          {
            dpCode: 'BION003',
            fiscalYear: '2018-2019',
            status: 'unknown',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2017',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null, type: '', comment: '', errorStatus: 'Incomplete',
            },
          },
        ],
        historicalData: [
          {
            dpCode: 'BION003',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2017',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BION003',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
    ],
  },
  {
    taskId: '0003',
    pillar: 'Governance',
    company: 'Manglore Refinery Petrochemicals Ltd',
    fiscalYear: '2018-2019, 2019-2020',
    status: 'Yet to start',
    dpCodesData: [
      {
        dpCode: 'BIOP002',
        fiscalYear: '2018-2019, 2019-2020',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        comments: [
          {
            author: 'Quality Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Company Representative', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
        ],
        currentData: [
          {
            dpCode: 'BIOP002',
            fiscalYear: '2018-2019',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null, type: '', comment: '', errorStatus: 'Incomplete',
            },
          },
          {
            dpCode: 'BIOP002',
            fiscalYear: '2019-2020',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null, type: '', comment: '', errorStatus: 'Incomplete',
            },
          },
        ],
        historicalData: [
          {
            dpCode: 'BIOP002',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BIOP002',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'No',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
      {
        dpCode: 'BION002',
        fiscalYear: '2018-2019, 2019-2020',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        comments: [
          {
            author: 'Quality Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Company Representative', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
        ],
        currentData: [
          {
            dpCode: 'BION002',
            fiscalYear: '2018-2019',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '10000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null, type: '', comment: '', errorStatus: 'Incomplete',
            },
          },
          {
            dpCode: 'BION002',
            fiscalYear: '2019-2020',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '10000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null, type: '', comment: '', errorStatus: 'Incomplete',
            },
          },
        ],
        historicalData: [
          {
            dpCode: 'BION002',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '10000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BION002',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '23000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
      {
        dpCode: 'BION003',
        fiscalYear: '2018-2019, 2019-2020',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        comments: [
          {
            author: 'Quality Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Company Representative', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
        ],
        currentData: [
          {
            dpCode: 'BION003',
            fiscalYear: '2018-2019',
            status: 'unknown',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2017',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null, type: '', comment: '', errorStatus: 'Incomplete',
            },
          },
          {
            dpCode: 'BION003',
            fiscalYear: '2019-2020',
            status: 'unknown',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2017',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null, type: '', comment: '', errorStatus: 'Incomplete',
            },
          },
        ],
        historicalData: [
          {
            dpCode: 'BION003',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2017',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BION003',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
    ],
  },
];

export const COMPANY_REP_DATA = [
  {
    taskId: '0001',
    pillar: 'Environmental',
    company: 'Manglore Refinery Petrochemicals Ltd',
    fiscalYear: '2018-2019, 2019-2020',
    status: 'Yet to start',
    dpCodesData: [
      {
        dpCode: 'BIOP002',
        fiscalYear: '2018-2019, 2019-2020',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        comments: [
          {
            author: 'Quality Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Company Representative', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
        ],
        currentData: [
          {
            dpCode: 'BIOP002',
            fiscalYear: '2018-2019',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null,
              refData: {
                textSnippet: '',
                pageNo: '',
                screenShot: null,
                response: '',
                source: null,
                url: '',
                publicationDate: '',
              },
              comment: '',
              errorStatus: 'Incomplete',
            },
          },
          {
            dpCode: 'BIOP002',
            fiscalYear: '2019-2020',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null,
              refData: {
                textSnippet: '',
                pageNo: '',
                screenShot: null,
                response: '',
                source: null,
                url: '',
                publicationDate: '',
              },
              comment: '',
              errorStatus: 'Incomplete',
            },
          },
        ],
        historicalData: [
          {
            dpCode: 'BIOP002',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BIOP002',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'No',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
      {
        dpCode: 'BION002',
        fiscalYear: '2018-2019, 2019-2020',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        comments: [
          {
            author: 'Quality Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Company Representative', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
        ],
        currentData: [
          {
            dpCode: 'BION002',
            fiscalYear: '2018-2019',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '10000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null,
              refData: {
                textSnippet: '',
                pageNo: '',
                screenShot: null,
                response: '',
                source: null,
                url: '',
                publicationDate: '',
              },
              comment: '',
              errorStatus: 'Incomplete',
            },
          },
          {
            dpCode: 'BION002',
            fiscalYear: '2019-2020',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '10000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null,
              refData: {
                textSnippet: '',
                pageNo: '',
                screenShot: null,
                response: '',
                source: null,
                url: '',
                publicationDate: '',
              },
              comment: '',
              errorStatus: 'Incomplete',
            },
          },
        ],
        historicalData: [
          {
            dpCode: 'BION002',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '10000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BION002',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '23000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
      {
        dpCode: 'BION003',
        fiscalYear: '2018-2019, 2019-2020',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        comments: [
          {
            author: 'Quality Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Company Representative', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
        ],
        currentData: [
          {
            dpCode: 'BION003',
            fiscalYear: '2018-2019',
            status: 'unknown',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2017',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null,
              refData: {
                textSnippet: '',
                pageNo: '',
                screenShot: null,
                response: '',
                source: null,
                url: '',
                publicationDate: '',
              },
              comment: '',
              errorStatus: 'Incomplete',
            },
          },
          {
            dpCode: 'BION003',
            fiscalYear: '2019-2020',
            status: 'unknown',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2017',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null,
              refData: {
                textSnippet: '',
                pageNo: '',
                screenShot: null,
                response: '',
                source: null,
                url: '',
                publicationDate: '',
              },
              comment: '',
              errorStatus: 'Incomplete',
            },
          },
        ],
        historicalData: [
          {
            dpCode: 'BION003',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2017',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BION003',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
    ],
  },
  {
    taskId: '0002',
    pillar: 'Social',
    company: 'Manglore Refinery Petrochemicals Ltd',
    fiscalYear: '2018-2019, 2019-2020',
    status: 'In progress',
    dpCodesData: [
      {
        dpCode: 'BIOP002',
        fiscalYear: '2018-2019, 2019-2020',
        status: 'Completed',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        comments: [
          {
            author: 'Quality Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Company Representative', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
        ],
        currentData: [
          {
            dpCode: 'BIOP002',
            fiscalYear: '2018-2019',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: true,
              refData: {
                textSnippet: 'Snippet 1',
                pageNo: '46',
                screenShot: null,
                response: 'Yes',
                source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
                url: '',
                publicationDate: '',
              },
              comment: 'Comment 1',
              errorStatus: 'Completed',
            },
          },
          {
            dpCode: 'BIOP002',
            fiscalYear: '2019-2020',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: true,
              refData: {
                textSnippet: 'Snippet 2',
                pageNo: '44',
                screenShot: null,
                response: 'No',
                source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
                url: '',
                publicationDate: '',
              },
              comment: 'Comment 2',
              errorStatus: 'Completed',
            },
          },
        ],
        historicalData: [
          {
            dpCode: 'BIOP002',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BIOP002',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'No',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
      {
        dpCode: 'BION002',
        fiscalYear: '2018-2019, 2019-2020',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        comments: [
          {
            author: 'Quality Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Company Representative', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
        ],
        currentData: [
          {
            dpCode: 'BION002',
            fiscalYear: '2018-2019',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '10000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null,
              refData: {
                textSnippet: '',
                pageNo: '',
                screenShot: null,
                response: '',
                source: null,
                url: '',
                publicationDate: '',
              },
              comment: '',
              errorStatus: 'Incomplete',
            },
          },
          {
            dpCode: 'BION002',
            fiscalYear: '2019-2020',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '10000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null,
              refData: {
                textSnippet: '',
                pageNo: '',
                screenShot: null,
                response: '',
                source: null,
                url: '',
                publicationDate: '',
              },
              comment: '',
              errorStatus: 'Incomplete',
            },
          },
        ],
        historicalData: [
          {
            dpCode: 'BION002',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '10000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BION002',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '23000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
      {
        dpCode: 'BION003',
        fiscalYear: '2018-2019, 2019-2020',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        comments: [
          {
            author: 'Quality Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Company Representative', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
        ],
        currentData: [
          {
            dpCode: 'BION003',
            fiscalYear: '2018-2019',
            status: 'unknown',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2017',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null,
              refData: {
                textSnippet: '',
                pageNo: '',
                screenShot: null,
                response: '',
                source: null,
                url: '',
                publicationDate: '',
              },
              comment: '',
              errorStatus: 'Incomplete',
            },
          },
          {
            dpCode: 'BION003',
            fiscalYear: '2019-2020',
            status: 'unknown',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2017',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null,
              refData: {
                textSnippet: '',
                pageNo: '',
                screenShot: null,
                response: '',
                source: null,
                url: '',
                publicationDate: '',
              },
              comment: '',
              errorStatus: 'Incomplete',
            },
          },
        ],
        historicalData: [
          {
            dpCode: 'BION003',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2017',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BION003',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
    ],
  },
  {
    taskId: '0003',
    pillar: 'Governance',
    company: 'Manglore Refinery Petrochemicals Ltd',
    fiscalYear: '2018-2019, 2019-2020',
    status: 'Yet to start',
    dpCodesData: [
      {
        dpCode: 'BIOP002',
        fiscalYear: '2018-2019, 2019-2020',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        comments: [
          {
            author: 'Quality Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Company Representative', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
        ],
        currentData: [
          {
            dpCode: 'BIOP002',
            fiscalYear: '2018-2019',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null,
              refData: {
                textSnippet: '',
                pageNo: '',
                screenShot: null,
                response: '',
                source: null,
                url: '',
                publicationDate: '',
              },
              comment: '',
              errorStatus: 'Incomplete',
            },
          },
          {
            dpCode: 'BIOP002',
            fiscalYear: '2019-2020',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null,
              refData: {
                textSnippet: '',
                pageNo: '',
                screenShot: null,
                response: '',
                source: null,
                url: '',
                publicationDate: '',
              },
              comment: '',
              errorStatus: 'Incomplete',
            },
          },
        ],
        historicalData: [
          {
            dpCode: 'BIOP002',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Yes',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BIOP002',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Does the company have a biodiversity restoration program ?',
            dataType: 'text',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'No',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
      {
        dpCode: 'BION002',
        fiscalYear: '2018-2019, 2019-2020',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        comments: [
          {
            author: 'Quality Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Company Representative', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
        ],
        currentData: [
          {
            dpCode: 'BION002',
            fiscalYear: '2018-2019',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '10000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null,
              refData: {
                textSnippet: '',
                pageNo: '',
                screenShot: null,
                response: '',
                source: null,
                url: '',
                publicationDate: '',
              },
              comment: '',
              errorStatus: 'Incomplete',
            },
          },
          {
            dpCode: 'BION002',
            fiscalYear: '2019-2020',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '10000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null,
              refData: {
                textSnippet: '',
                pageNo: '',
                screenShot: null,
                response: '',
                source: null,
                url: '',
                publicationDate: '',
              },
              comment: '',
              errorStatus: 'Incomplete',
            },
          },
        ],
        historicalData: [
          {
            dpCode: 'BION002',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '10000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BION002',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: "Fines paid due to the impact of the company's operations on biodiversity",
            dataType: 'number',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: '23000',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
      {
        dpCode: 'BION003',
        fiscalYear: '2018-2019, 2019-2020',
        status: 'Yet to start',
        isStandAloneOrMatrix: 'Standalone',
        keyIssue: 'Biodiversity impact',
        comments: [
          {
            author: 'Quality Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Analyst', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
          {
            author: 'Company Representative', content: 'Comment', fiscalYear: '2018-2019', dateTime: 'Thu Jun 24 2018',
          },
        ],
        currentData: [
          {
            dpCode: 'BION003',
            fiscalYear: '2018-2019',
            status: 'unknown',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2017',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null,
              refData: {
                textSnippet: '',
                pageNo: '',
                screenShot: null,
                response: '',
                source: null,
                url: '',
                publicationDate: '',
              },
              comment: '',
              errorStatus: 'Incomplete',
            },
          },
          {
            dpCode: 'BION003',
            fiscalYear: '2019-2020',
            status: 'unknown',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2017',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
            error: {
              isThere: null,
              refData: {
                textSnippet: '',
                pageNo: '',
                screenShot: null,
                response: '',
                source: null,
                url: '',
                publicationDate: '',
              },
              comment: '',
              errorStatus: 'Incomplete',
            },
          },
        ],
        historicalData: [
          {
            dpCode: 'BION003',
            fiscalYear: '2017-2018',
            status: 'Completed',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2017-2018',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2017',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2017' },
          },
          {
            dpCode: 'BION003',
            fiscalYear: '2016-2017',
            status: 'Completed',
            description: 'Fine Due Date',
            dataType: 'date',
            textSnippet: 'Biodiversity Snippet 2016-2017',
            pageNo: '59',
            screenShot: 'https://esgds.io/images/home/logo.png',
            response: 'Tue May 01 2016',
            source: { sourceName: 'Annual Report', url: 'https://admin.mrpl.co.in/img/UploadedFiles/AnnualReport/Files/1c7d3b3b1d7f4c65b46e50c3422a1bdb.pdf', publicationDate: 'Tue May 04 2016' },
          },
        ],
      },
    ],
  },
];
