export default {
  apiEndPoints: {
    getLogin: 'auth',
    getOtp: 'auth/auth-otp',
    getForgotPassword: 'password-resets',
    getCompanylist: 'companies',
    getBatchlist: 'batches',
    getOnboard: 'users/new-onboard',
    createBatch: 'batches/create',
    clientTaxonomy: 'clientTaxonomies',
    getKeyIssues: 'key_issues',
    getMasterTaxonomy: 'taxonomies',
    getRoles: 'role',
    roleAssignmentEdit: 'users/assign-role',
    getRoleFileOnboarding: 'users/new-onboard/upload-emails-file',
    getRoleListOnboarding: 'users/new-onboard/send-mails',
    newClientTaxonomy: 'clientTaxonomies/create',
    getFilterUsers: 'users/filter-user',
    userUpdate: 'users',
    uploadTaxonomy: 'datapoints/upload',
    getPendingTasksList: 'taskAssignments/my-tasks',
    putMatrixMember: '/companies/add/member',
    getTask: 'datapoints/list',
    gettaskDetails: '/taskAssignments/getGroupAndBatches',
    getpillarTaxonomy: 'categories/taxonomy-pillars',
    unassignedBatches: 'batches/all/unassigned',
    createGroup: 'groups/create',
    getGroupList: 'groups',
  },
  apiBaseUrl: {
    dev: 'http://65.1.140.116:9010/',
    prod: 'http://65.1.140.116:9010/',
  },
};
